/*
Copyright 2019 The oooops Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/liubog2008/oooops/pkg/apis/mario/v1alpha1"
	scheme "github.com/liubog2008/oooops/pkg/client/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PipesGetter has a method to return a PipeInterface.
// A group's client should implement this interface.
type PipesGetter interface {
	Pipes(namespace string) PipeInterface
}

// PipeInterface has methods to work with Pipe resources.
type PipeInterface interface {
	Create(*v1alpha1.Pipe) (*v1alpha1.Pipe, error)
	Update(*v1alpha1.Pipe) (*v1alpha1.Pipe, error)
	UpdateStatus(*v1alpha1.Pipe) (*v1alpha1.Pipe, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Pipe, error)
	List(opts v1.ListOptions) (*v1alpha1.PipeList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Pipe, err error)
	PipeExpansion
}

// pipes implements PipeInterface
type pipes struct {
	client rest.Interface
	ns     string
}

// newPipes returns a Pipes
func newPipes(c *MarioV1alpha1Client, namespace string) *pipes {
	return &pipes{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the pipe, and returns the corresponding pipe object, and an error if there is any.
func (c *pipes) Get(name string, options v1.GetOptions) (result *v1alpha1.Pipe, err error) {
	result = &v1alpha1.Pipe{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("pipes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Pipes that match those selectors.
func (c *pipes) List(opts v1.ListOptions) (result *v1alpha1.PipeList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.PipeList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("pipes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested pipes.
func (c *pipes) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("pipes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a pipe and creates it.  Returns the server's representation of the pipe, and an error, if there is any.
func (c *pipes) Create(pipe *v1alpha1.Pipe) (result *v1alpha1.Pipe, err error) {
	result = &v1alpha1.Pipe{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("pipes").
		Body(pipe).
		Do().
		Into(result)
	return
}

// Update takes the representation of a pipe and updates it. Returns the server's representation of the pipe, and an error, if there is any.
func (c *pipes) Update(pipe *v1alpha1.Pipe) (result *v1alpha1.Pipe, err error) {
	result = &v1alpha1.Pipe{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("pipes").
		Name(pipe.Name).
		Body(pipe).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *pipes) UpdateStatus(pipe *v1alpha1.Pipe) (result *v1alpha1.Pipe, err error) {
	result = &v1alpha1.Pipe{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("pipes").
		Name(pipe.Name).
		SubResource("status").
		Body(pipe).
		Do().
		Into(result)
	return
}

// Delete takes name of the pipe and deletes it. Returns an error if one occurs.
func (c *pipes) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("pipes").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *pipes) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("pipes").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched pipe.
func (c *pipes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Pipe, err error) {
	result = &v1alpha1.Pipe{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("pipes").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
