apiVersion: mario.oooops.com/v1alpha1
kind: Mario
metadata:
  name: oooops
spec:
  actions:
  - name: compile
    template:
      image: golang:1.13.6
      command:
      - go
      - build
      - -v
      - .
    workingDir: /go/src/github.com/liubog2008/oooops
    version:
      envName: VERSION
