/*
Copyright 2020 The oooops Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/liubog2008/oooops/pkg/apis/mario/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMarios implements MarioInterface
type FakeMarios struct {
	Fake *FakeMarioV1alpha1
	ns   string
}

var mariosResource = schema.GroupVersionResource{Group: "mario.oooops.com", Version: "v1alpha1", Resource: "marios"}

var mariosKind = schema.GroupVersionKind{Group: "mario.oooops.com", Version: "v1alpha1", Kind: "Mario"}

// Get takes name of the mario, and returns the corresponding mario object, and an error if there is any.
func (c *FakeMarios) Get(name string, options v1.GetOptions) (result *v1alpha1.Mario, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(mariosResource, c.ns, name), &v1alpha1.Mario{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Mario), err
}

// List takes label and field selectors, and returns the list of Marios that match those selectors.
func (c *FakeMarios) List(opts v1.ListOptions) (result *v1alpha1.MarioList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(mariosResource, mariosKind, c.ns, opts), &v1alpha1.MarioList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MarioList{ListMeta: obj.(*v1alpha1.MarioList).ListMeta}
	for _, item := range obj.(*v1alpha1.MarioList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested marios.
func (c *FakeMarios) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(mariosResource, c.ns, opts))

}

// Create takes the representation of a mario and creates it.  Returns the server's representation of the mario, and an error, if there is any.
func (c *FakeMarios) Create(mario *v1alpha1.Mario) (result *v1alpha1.Mario, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(mariosResource, c.ns, mario), &v1alpha1.Mario{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Mario), err
}

// Update takes the representation of a mario and updates it. Returns the server's representation of the mario, and an error, if there is any.
func (c *FakeMarios) Update(mario *v1alpha1.Mario) (result *v1alpha1.Mario, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(mariosResource, c.ns, mario), &v1alpha1.Mario{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Mario), err
}

// Delete takes name of the mario and deletes it. Returns an error if one occurs.
func (c *FakeMarios) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(mariosResource, c.ns, name), &v1alpha1.Mario{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMarios) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(mariosResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.MarioList{})
	return err
}

// Patch applies the patch and returns the patched mario.
func (c *FakeMarios) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Mario, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(mariosResource, c.ns, name, pt, data, subresources...), &v1alpha1.Mario{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Mario), err
}
