/*
Copyright 2019 The oooops Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/liubog2008/oooops/pkg/apis/mario/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePipes implements PipeInterface
type FakePipes struct {
	Fake *FakeMarioV1alpha1
	ns   string
}

var pipesResource = schema.GroupVersionResource{Group: "mario.oooops.com", Version: "v1alpha1", Resource: "pipes"}

var pipesKind = schema.GroupVersionKind{Group: "mario.oooops.com", Version: "v1alpha1", Kind: "Pipe"}

// Get takes name of the pipe, and returns the corresponding pipe object, and an error if there is any.
func (c *FakePipes) Get(name string, options v1.GetOptions) (result *v1alpha1.Pipe, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(pipesResource, c.ns, name), &v1alpha1.Pipe{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Pipe), err
}

// List takes label and field selectors, and returns the list of Pipes that match those selectors.
func (c *FakePipes) List(opts v1.ListOptions) (result *v1alpha1.PipeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(pipesResource, pipesKind, c.ns, opts), &v1alpha1.PipeList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PipeList{ListMeta: obj.(*v1alpha1.PipeList).ListMeta}
	for _, item := range obj.(*v1alpha1.PipeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested pipes.
func (c *FakePipes) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(pipesResource, c.ns, opts))

}

// Create takes the representation of a pipe and creates it.  Returns the server's representation of the pipe, and an error, if there is any.
func (c *FakePipes) Create(pipe *v1alpha1.Pipe) (result *v1alpha1.Pipe, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(pipesResource, c.ns, pipe), &v1alpha1.Pipe{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Pipe), err
}

// Update takes the representation of a pipe and updates it. Returns the server's representation of the pipe, and an error, if there is any.
func (c *FakePipes) Update(pipe *v1alpha1.Pipe) (result *v1alpha1.Pipe, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(pipesResource, c.ns, pipe), &v1alpha1.Pipe{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Pipe), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePipes) UpdateStatus(pipe *v1alpha1.Pipe) (*v1alpha1.Pipe, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(pipesResource, "status", c.ns, pipe), &v1alpha1.Pipe{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Pipe), err
}

// Delete takes name of the pipe and deletes it. Returns an error if one occurs.
func (c *FakePipes) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(pipesResource, c.ns, name), &v1alpha1.Pipe{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePipes) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(pipesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.PipeList{})
	return err
}

// Patch applies the patch and returns the patched pipe.
func (c *FakePipes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Pipe, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(pipesResource, c.ns, name, pt, data, subresources...), &v1alpha1.Pipe{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Pipe), err
}
