/*
Copyright 2020 The oooops Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	mariov1alpha1 "github.com/liubog2008/oooops/pkg/apis/mario/v1alpha1"
	clientset "github.com/liubog2008/oooops/pkg/client/clientset"
	internalinterfaces "github.com/liubog2008/oooops/pkg/client/informers/internalinterfaces"
	v1alpha1 "github.com/liubog2008/oooops/pkg/client/listers/mario/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PipeInformer provides access to a shared informer and lister for
// Pipes.
type PipeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.PipeLister
}

type pipeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPipeInformer constructs a new informer for Pipe type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPipeInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPipeInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPipeInformer constructs a new informer for Pipe type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPipeInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MarioV1alpha1().Pipes(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MarioV1alpha1().Pipes(namespace).Watch(options)
			},
		},
		&mariov1alpha1.Pipe{},
		resyncPeriod,
		indexers,
	)
}

func (f *pipeInformer) defaultInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPipeInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *pipeInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&mariov1alpha1.Pipe{}, f.defaultInformer)
}

func (f *pipeInformer) Lister() v1alpha1.PipeLister {
	return v1alpha1.NewPipeLister(f.Informer().GetIndexer())
}
